# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14vHES3wXcuj5gTfbUH_3op3H5sesHaMc
"""

import requests

api_link = "https://samples.openweathermap.org/data/2.5/forecast/hourly?q=London,us&appid=b6907d289e10d714a6e88b30761fae22"

api_data = requests.get(api_link)
api_data_json = api_data.json()

date_list = []

weather_list = api_data_json["list"]


def get_temperature(date):
  temp_list =[]
  for i in range (0,len(weather_list)):
    if (date == weather_list[i]["dt_txt"][:10]):
      temp_list.append(weather_list[i]['main']['temp'])
  avg_temp = round(sum(temp_list)/len(temp_list),2)
  return avg_temp

def get_wind_speed(date):
  wind_list = []
  for i in range (0,len(weather_list)):
    if (date == weather_list[i]["dt_txt"][:10]):
      wind_list.append(weather_list[i]['wind']['speed'])
  avg_wind = round(sum(wind_list)/len(wind_list),2)
  return avg_wind

def get_pressure(date):
  pressure_list = []
  for i in range (0,len(weather_list)):
    if (date == weather_list[i]["dt_txt"][:10]):
      pressure_list.append(weather_list[i]['main']['pressure'])
  avg_pressure = round(sum(pressure_list)/len(pressure_list),2)
  return avg_pressure
      

def weather():
  is_over = False
  while not is_over:
    choice = input("Please choose an option 1:Temperature, 2:Wind Speed , 3:Pressure, 0:Exit\n")
    if choice == "1":
      dates = input("Please enter the date (yyyy-mm-dd)")
      date_temp = get_temperature(dates)
      print(f"The temperature on {dates} is {date_temp}")
    if choice == "2":
      date = input("Please enter the date (yyyy-mm-dd)")
      date_wind = get_wind_speed(date)
      print(f"The wind speed on {dates} is {date_wind}")
    if choice == "3":
      date = input("Please enter the date (yyyy-mm-dd)")
      date_pressure = get_pressure(date)
      print(f"The pressure on {date} is {date_pressure} PSI")
    if choice == "0":
      is_over = True

weather()